# Generated by Django 3.1.4 on 2021-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210101_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='back_cam_lens',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='لنز'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='front_cam_lens',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='لنز'),
        ),
    ]
