# Generated by Django 3.1.4 on 2021-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20210101_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='other_ui',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رابط کاربری'),
        ),
    ]
