# Generated by Django 3.1.4 on 2021-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20210101_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='hardware_ram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='حافظه رم'),
        ),
    ]
