# Generated by Django 3.1.4 on 2021-01-01 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_auto_20210101_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج در سایت'),
        ),
    ]
