# Generated by Django 3.1.4 on 2021-01-01 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_phone_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='add_date',
        ),
        migrations.AddField(
            model_name='phone',
            name='add_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان درج در سایت'),
        ),
    ]
