# Generated by Django 3.1.4 on 2021-01-01 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_auto_20210101_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='add_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='زمان درج در سایت'),
        ),
    ]
