# Generated by Django 3.1.4 on 2021-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0010_phone_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='about',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='درباره'),
        ),
    ]
