# Generated by Django 3.1.4 on 2021-01-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_auto_20210103_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'اپل'), ('Xiaomi', 'Xiaomi'), ('Nokia', 'Nokia'), ('Huawei', 'Huawei')], max_length=7, verbose_name='برند'),
        ),
    ]
